### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by yedidmh** [Valentinishe/tic-tac-toe#2]
Following the instructions in the README fails to work.

`redis` and `mongo` are installed per your instructions but you did not include any instruction to start them up so that the CLI can connect to them, therefore the following error occurs when running `npm run migrate`:

```
Error connection to MONGO DB { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
```

Ideally this should be scripted, but it's ok if it's just instructions.

**Comment by Valentinishe** [comment]
I resolve steps.
Thanks.
